---
title: NATIVEKA
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
subtitle:
email: asanchez@nativeka.tk
description: We focus on NodeJS, Wix Code, Jekyll, JavaScript, Kony<br /> Python Flask, React, React Native, Jasonette, ThunkableX
baseurl: ''
url: https://www.nativeka.tk
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: "(716) 555-5555"
tiles-source: pages
tiles-count: 6
500px_url:
facebook_url:
github_url:
gitlab_url: https://github.com/auniverse4
googleplus_url:
instagram_url: 
linkedin_url: https://www.linkedin.com/company/nativeka
pinterest_url:
slack_url:
twitter_url:
markdown: kramdown
sass:
  style: compressed
