---
title: Forty
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
subtitle: by HTML5 UP
email: youremailaddress@gmail.com
description: We work with awesome people and companies from
​USA, Canada, England, Australia, India to turn ideas into digital products!
​We proudly use Wix Code, NodeJS, Weebly CMS, Python, Thunkable, Jasonette, Kony

baseurl: ''
url: https://www.nativeka.tk
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: "(716) 555-5555"
tiles-source: pages
tiles-count: 6
500px_url:
facebook_url: https://facebook.com
github_url: https://github.com/auniverse4
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/company/nativeka
pinterest_url:
slack_url:
twitter_url:
markdown: kramdown
sass:
  style: compressed
