---
title: Stackk
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
subtitle:
email: asanchez@nativeka.tk
description: WE ARE STAKK! PREVIOUSLY NATIVEKA NodeJS, Wix Code, Jekyll, JavaScript, Kony, Python,<br /> React, Shopify, React Native, Jasonette, ThunkableX
baseurl: ''
url: https://www.nativeka.tk
author:
street_address:
city: Alajuela
state: Alajuela
zip_code: 55555
country: Costa Rica
phone: "(506) 6468-8599"
tiles-source: pages
tiles-count: 6
500px_url:
facebook_url:
github_url: https://github.com/auniverse4
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/company/nativeka
pinterest_url:
slack_url:
twitter_url:
markdown: kramdown
sass:
  style: compressed
